# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Latipov Mehrob
title: Backend Developer
email: popkorn.passport@gmail.com
website: github.com/lmboom

# Social links
#twitter_username: lmboom
github_username:  lmboom
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: lmboom
linkedin_username: lmboom
# pinterest_username: jekyll
#youtube_username: lbmoom
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Mehrob and I'm a backend developer. I also have experience in DevOps and Frontend.

  Skills: <mark>GO(Golang)</mark>  <mark>PHP(Laravel, Symfony)</mark>  <mark>Docker</mark> <mark>CI/CD</mark> <mark>ELK</mark>  <mark>MQ(Kafka, RabbitMQ)</mark>
  Frontend: <mark>CSS</mark>  <mark>JS(VueJS, ReactJS)</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Also I like:
   - Pizza
   - Gym
   - IOS development

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: true
